### ISSUE TITLE
Return type for some methods in ISqlDataAccessor<T>

### ISSUE THREAD

**Issue by alexars** [Bledhard/GreenShop#57]
Edit and Delete methods in  ISqlDataAccessor<T> that returns int. 
My suggestion is to change int to bool, as at upper levels we check it for true or false.

**Comment by dreytko** [comment]
The reason why both these methods return int is that Dapper itself returns a number of rows that were affected. As ISqlDataAccessor is mostly a wrapper for the Dapper with proper scripts, I don't think we should change the output, as we can still handle these ints however we want - I personally was just comparing this int with 1 to get the boolean.
